#!/usr/bin/env python3
"""
QuoteCraft Pro - Backend Server & Admin API
Zero-dependency Python 3 HTTP Server with SQLite Database

Features:
- REST API for quotes, company master config, and analytics
- Admin Authentication (Username: ADMIN, Password: kehansri888)
- Token-based Session Management
- SQLite Database Storage (database.db)
- Static File Serving for Single-Page Application
"""

import http.server
import socketserver
import json
import sqlite3
import hashlib
import secrets
import os
import mimetypes
import urllib.parse
from datetime import datetime, timedelta

PORT = 8899
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "database.db")
STATIC_DIR = os.path.dirname(os.path.abspath(__file__))

# Default Admin & Sales Credentials
DEFAULT_ADMIN_USER = "ADMIN"
DEFAULT_ADMIN_PASS = "kehansri888"

DEFAULT_SALES_USER = "SALES"
DEFAULT_SALES_PASS = "sales888"

# Active Sessions: { session_token: { username: "ADMIN" | "SALES", role: "admin" | "sales", expires_at: datetime } }
SESSIONS = {}


def get_db():
    """Returns a SQLite connection with row factory"""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Initializes database tables and default company settings"""
    conn = get_db()
    cur = conn.cursor()

    # 1. Config Table (With Admin & Salesperson Auth)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS config (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            bank_name TEXT NOT NULL,
            account_name TEXT NOT NULL,
            account_number TEXT NOT NULL,
            ifsc_code TEXT NOT NULL,
            branch_address TEXT NOT NULL,
            company_name TEXT NOT NULL,
            company_email TEXT,
            company_phone TEXT,
            company_address TEXT,
            admin_username TEXT NOT NULL,
            admin_password_hash TEXT NOT NULL,
            sales_username TEXT DEFAULT 'SALES',
            sales_password_hash TEXT,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Check & migrate columns for existing databases
    try:
        cur.execute("ALTER TABLE config ADD COLUMN sales_username TEXT DEFAULT 'SALES'")
    except Exception:
        pass

    try:
        cur.execute("ALTER TABLE config ADD COLUMN sales_password_hash TEXT")
    except Exception:
        pass

    # Bank 1 & Bank 2 column migrations
    for col, default_val in [
        ("bank_label", "'KehanSri Solar (Primary)'"),
        ("bank2_name", "'HDFC BANK'"),
        ("bank2_account_name", "'K Energy Solutions'"),
        ("bank2_account_number", "'50200088991122'"),
        ("bank2_ifsc_code", "'HDFC0000456'"),
        ("bank2_branch_address", "'Gachibowli, Hyderabad, Telangana: 500032'"),
        ("bank2_label", "'K Energy Solutions (2nd Company)'")
    ]:
        try:
            cur.execute(f"ALTER TABLE config ADD COLUMN {col} TEXT DEFAULT {default_val}")
        except Exception:
            pass

    # 2. Quotes Table (All quotes generated by sales reps)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS quotes (
            id TEXT PRIMARY KEY,
            quote_number TEXT NOT NULL,
            client_name TEXT NOT NULL,
            client_phone TEXT,
            client_email TEXT,
            client_address TEXT,
            kw_capacity REAL NOT NULL,
            partner_brand TEXT NOT NULL,
            structure_type TEXT,
            total_cost REAL NOT NULL,
            subsidy REAL NOT NULL,
            net_cost REAL NOT NULL,
            sales_rep TEXT,
            sales_username TEXT,
            installer_brand TEXT,
            status TEXT DEFAULT 'Generated',
            quote_json TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    try:
        cur.execute("ALTER TABLE quotes ADD COLUMN sales_username TEXT")
    except Exception:
        pass

    try:
        cur.execute("ALTER TABLE quotes ADD COLUMN installer_brand TEXT")
    except Exception:
        pass

    # 3. Users Table (Admin and Sales Staff Accounts)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            display_name TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT DEFAULT 'sales',
            phone TEXT,
            email TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Populate Default Config if not exists
    cur.execute("SELECT COUNT(*) as cnt FROM config WHERE id = 1")
    admin_hash = hashlib.sha256(DEFAULT_ADMIN_PASS.encode("utf-8")).hexdigest()
    sales_hash = hashlib.sha256(DEFAULT_SALES_PASS.encode("utf-8")).hexdigest()

    if cur.fetchone()["cnt"] == 0:
        cur.execute("""
            INSERT INTO config (
                id, bank_name, account_name, account_number, ifsc_code, branch_address,
                company_name, company_email, company_phone, company_address,
                admin_username, admin_password_hash, sales_username, sales_password_hash
            ) VALUES (
                1, 'ICICI BANK', 'KehanSri Solar', '38205006367', 'ICIC0000382',
                'Banjara Hills, Road No 12, Hyderabad: 500034',
                'KehanSri Solar', 'sales@kehansrisolar.com', '+91 9493858086',
                'Plot 42, Silicon Valley, Hyderabad, Telangana: 500081',
                ?, ?, ?, ?
            )
        """, (DEFAULT_ADMIN_USER, admin_hash, DEFAULT_SALES_USER, sales_hash))
    else:
        # Ensure sales password hash is set if empty
        cur.execute("""
            UPDATE config SET 
                sales_username = COALESCE(sales_username, 'SALES'),
                sales_password_hash = COALESCE(sales_password_hash, ?)
            WHERE id = 1 AND (sales_password_hash IS NULL OR sales_password_hash = '')
        """, (sales_hash,))

    # Seed Admin User if not exists
    cur.execute("SELECT COUNT(*) as cnt FROM users WHERE username = 'ADMIN'")
    if cur.fetchone()["cnt"] == 0:
        cur.execute("""
            INSERT INTO users (id, username, display_name, password_hash, role, is_active)
            VALUES ('usr_admin_master', 'ADMIN', 'Administrator', ?, 'admin', 1)
        """, (admin_hash,))

    # Seed Default Sales User if table has no sales users
    cur.execute("SELECT COUNT(*) as cnt FROM users WHERE role = 'sales'")
    if cur.fetchone()["cnt"] == 0:
        cur.execute("""
            INSERT INTO users (id, username, display_name, password_hash, role, phone, email, is_active)
            VALUES ('usr_sales_default', 'SALES', 'Sales Executive', ?, 'sales', '+91 9493858086', 'sales@kehansrisolar.com', 1)
        """, (sales_hash,))

    conn.commit()
    conn.close()
    print("✅ SQLite Database initialized with Users:", DB_PATH)


def verify_session(token):
    """Checks if session token is valid and not expired"""
    if not token or token not in SESSIONS:
        return None
    session = SESSIONS[token]
    if datetime.now() > session["expires_at"]:
        del SESSIONS[token]
        return None
    return session


def verify_admin_session(token):
    """Checks if session token belongs to an Admin"""
    session = verify_session(token)
    return bool(session and session.get("role") == "admin")


def verify_sales_session(token):
    """Checks if session token belongs to a Salesperson or Admin"""
    session = verify_session(token)
    return bool(session and session.get("role") in ["sales", "admin"])


class QuoteCraftHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=STATIC_DIR, **kwargs)

    def send_json(self, data, status=200):
        response_bytes = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(response_bytes)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
        self.end_headers()
        self.wfile.write(response_bytes)

    def get_auth_token(self):
        auth_header = self.headers.get("Authorization", "")
        if auth_header.startswith("Bearer "):
            return auth_header[7:].strip()
        # Also check cookie if present
        cookie_header = self.headers.get("Cookie", "")
        if "admin_token=" in cookie_header:
            for part in cookie_header.split(";"):
                if part.strip().startswith("admin_token="):
                    return part.strip().split("=")[1]
        return None

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
        self.end_headers()

    def do_GET(self):
        parsed_url = urllib.parse.urlparse(self.path)
        path = parsed_url.path
        query = urllib.parse.parse_qs(parsed_url.query)

        # -------------------------------------------------------------
        # API Routes
        # -------------------------------------------------------------
        
        # 1. Public Company & Bank Config
        if path in ["/api/config", "/api/admin/config"]:
            conn = get_db()
            cur = conn.cursor()
            cur.execute("""
                SELECT bank_name, account_name, account_number, ifsc_code, branch_address, bank_label,
                       bank2_name, bank2_account_name, bank2_account_number, bank2_ifsc_code, bank2_branch_address, bank2_label,
                       company_name, company_email, company_phone, company_address, updated_at
                FROM config WHERE id = 1
            """)
            row = cur.fetchone()
            conn.close()
            if row:
                self.send_json({
                    "success": True,
                    "config": dict(row)
                })
            else:
                self.send_json({"success": False, "error": "Config not found"}, 404)
            return

        # 2. Check Admin & Sales Auth Status
        if path in ["/api/admin/check", "/api/auth/check"]:
            token = self.get_auth_token()
            session = verify_session(token)
            if session:
                self.send_json({
                    "authenticated": True,
                    "isAdmin": session.get("role") == "admin",
                    "isSales": session.get("role") in ["sales", "admin"],
                    "role": session.get("role"),
                    "username": session.get("username"),
                    "displayName": session.get("displayName") or session.get("username")
                })
            else:
                self.send_json({
                    "authenticated": False,
                    "isAdmin": False,
                    "isSales": False,
                    "role": None,
                    "username": None,
                    "displayName": None
                })
            return

        # 3. Admin: Get All Users (Sales Staff & Admin)
        if path == "/api/admin/users":
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            conn = get_db()
            cur = conn.cursor()
            cur.execute("""
                SELECT id, username, display_name, role, phone, email, is_active, created_at, updated_at
                FROM users
                ORDER BY role DESC, created_at ASC
            """)
            rows = [dict(r) for r in cur.fetchall()]
            conn.close()

            self.send_json({
                "success": True,
                "users": rows,
                "count": len(rows)
            })
            return

        # 3b. Get Active Salespersons List (for Admin Assignment & Filtering)
        if path == "/api/users/salespersons":
            conn = get_db()
            cur = conn.cursor()
            cur.execute("""
                SELECT id, username, display_name, role, phone, email, is_active
                FROM users
                WHERE is_active = 1
                ORDER BY role DESC, display_name ASC
            """)
            rows = [dict(r) for r in cur.fetchall()]
            conn.close()

            self.send_json({
                "success": True,
                "salespersons": rows,
                "count": len(rows)
            })
            return

        # 4. Get Quotations (Strict User-Level Data Isolation for Sales / Full Visibility for Admin)
        if path == "/api/quotes" or path == "/api/admin/quotes":
            token = self.get_auth_token()
            session = verify_session(token)
            if not session:
                self.send_json({"success": False, "error": "Unauthorized. Authentication required to access quotations."}, 401)
                return

            is_admin = session.get("role") == "admin"
            search = query.get("search", [""])[0].strip()
            sales_rep = query.get("sales_rep", [""])[0].strip()
            start_date = query.get("start_date", [""])[0].strip() or query.get("startDate", [""])[0].strip()
            end_date = query.get("end_date", [""])[0].strip() or query.get("endDate", [""])[0].strip()

            conn = get_db()
            cur = conn.cursor()

            sql = "SELECT * FROM quotes WHERE 1=1"
            params = []

            # DATA-LEVEL AUTHORIZATION FILTER:
            if not is_admin:
                # Normal sales user ONLY sees quotes created by / assigned to their account
                auth_username = (session.get("username") or "").strip()
                auth_display = (session.get("displayName") or auth_username).strip()
                sql += " AND (UPPER(COALESCE(sales_username, '')) = UPPER(?) OR (COALESCE(sales_username, '') = '' AND UPPER(sales_rep) = UPPER(?)))"
                params.extend([auth_username, auth_display])
            else:
                # Admin can view all quotations or filter by specific sales rep
                if sales_rep and sales_rep.lower() != "all":
                    sql += " AND (LOWER(sales_rep) = LOWER(?) OR LOWER(COALESCE(sales_username, '')) = LOWER(?))"
                    params.extend([sales_rep, sales_rep])

            if search:
                sql += " AND (client_name LIKE ? OR quote_number LIKE ? OR client_phone LIKE ? OR client_email LIKE ? OR sales_rep LIKE ? OR sales_username LIKE ?)"
                like_str = f"%{search}%"
                params.extend([like_str, like_str, like_str, like_str, like_str, like_str])

            if start_date:
                sql += " AND substr(created_at, 1, 10) >= ?"
                params.append(start_date)

            if end_date:
                sql += " AND substr(created_at, 1, 10) <= ?"
                params.append(end_date)

            sql += " ORDER BY created_at DESC LIMIT 500"
            cur.execute(sql, params)
            rows = [dict(r) for r in cur.fetchall()]
            conn.close()

            self.send_json({
                "success": True,
                "quotes": rows,
                "count": len(rows),
                "isolatedFor": session.get("username") if not is_admin else "ALL (Admin)"
            })
            return

        # 4b. Get Single Quotation by ID (Strict Ownership Verification)
        if path.startswith("/api/quotes/") or path.startswith("/api/admin/quotes/"):
            qid = path.replace("/api/admin/quotes/", "").replace("/api/quotes/", "").strip()
            if qid and not qid.startswith("delete") and not qid.startswith("update"):
                token = self.get_auth_token()
                session = verify_session(token)
                if not session:
                    self.send_json({"success": False, "error": "Unauthorized. Authentication required."}, 401)
                    return

                conn = get_db()
                cur = conn.cursor()
                cur.execute("SELECT * FROM quotes WHERE id = ? OR quote_number = ?", (qid, qid))
                row = cur.fetchone()
                conn.close()

                if not row:
                    self.send_json({"success": False, "error": "Quotation not found."}, 404)
                    return

                quote_dict = dict(row)
                is_admin = session.get("role") == "admin"
                sales_owner = (quote_dict.get("sales_username") or "").strip()

                # Normal users can ONLY view their own quotations
                if not is_admin:
                    auth_user = (session.get("username") or "").strip()
                    if sales_owner and sales_owner.upper() != auth_user.upper():
                        self.send_json({
                            "success": False,
                            "error": "Access Denied. You do not have permission to view quotations created by other users."
                        }, 403)
                        return

                try:
                    parsed_json = json.loads(quote_dict["quote_json"])
                except Exception:
                    parsed_json = quote_dict

                self.send_json({
                    "success": True,
                    "quote": parsed_json,
                    "record": quote_dict
                })
                return

        # 5. Admin: Get Sales Pipeline Stats & Day-Wise Breakdown
        if path == "/api/admin/stats":
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            start_date = query.get("start_date", [""])[0].strip() or query.get("startDate", [""])[0].strip()
            end_date = query.get("end_date", [""])[0].strip() or query.get("endDate", [""])[0].strip()

            conn = get_db()
            cur = conn.cursor()

            where_clause = "WHERE 1=1"
            params = []
            if start_date:
                where_clause += " AND substr(created_at, 1, 10) >= ?"
                params.append(start_date)
            if end_date:
                where_clause += " AND substr(created_at, 1, 10) <= ?"
                params.append(end_date)

            cur.execute(f"SELECT COUNT(*) as total_quotes, SUM(kw_capacity) as total_kw, SUM(total_cost) as total_revenue, SUM(net_cost) as total_net_revenue FROM quotes {where_clause}", params)
            agg = dict(cur.fetchone() or {})

            cur.execute(f"SELECT sales_rep, COUNT(*) as quote_count, SUM(kw_capacity) as total_kw, SUM(total_cost) as total_cost FROM quotes {where_clause} AND sales_rep IS NOT NULL AND sales_rep != '' GROUP BY sales_rep ORDER BY quote_count DESC LIMIT 20", params)
            rep_stats = [dict(r) for r in cur.fetchall()]

            cur.execute(f"SELECT partner_brand, COUNT(*) as cnt, SUM(kw_capacity) as kw FROM quotes {where_clause} GROUP BY partner_brand", params)
            brand_stats = [dict(r) for r in cur.fetchall()]

            # Day-wise quotation breakdown
            cur.execute(f"SELECT substr(created_at, 1, 10) as quote_date, COUNT(*) as count, SUM(kw_capacity) as total_kw, SUM(total_cost) as total_revenue FROM quotes {where_clause} GROUP BY substr(created_at, 1, 10) ORDER BY quote_date DESC LIMIT 60", params)
            daily_stats = [dict(r) for r in cur.fetchall()]

            conn.close()

            self.send_json({
                "success": True,
                "stats": {
                    "totalQuotes": agg.get("total_quotes") or 0,
                    "totalKw": round(agg.get("total_kw") or 0, 1),
                    "totalRevenue": round(agg.get("total_revenue") or 0, 2),
                    "totalNetRevenue": round(agg.get("total_net_revenue") or 0, 2),
                    "salesReps": rep_stats,
                    "brands": brand_stats,
                    "dailyStats": daily_stats
                }
            })
            return

        # 6. Download Daily Excel Report Endpoint
        if path in ["/api/reports/daily-excel", "/api/admin/reports/daily-excel"]:
            try:
                import scripts.daily_report_mailer as mailer
                ist_now = mailer.get_ist_now()
                ist_date_str = ist_now.strftime("%d %B %Y")
                date_file_str = ist_now.strftime("%Y-%m-%d")
                
                db_file = DB_PATH
                raw_quotes = mailer.fetch_quotes_from_sqlite(db_file, date_file_str)
                if not raw_quotes:
                    raw_quotes = mailer.generate_sample_quotes_for_demo(ist_now)
                
                parsed_quotes = [mailer.parse_quote_details(q) for q in raw_quotes]
                wb = mailer.build_excel_workbook(parsed_quotes, ist_date_str)
                
                import io
                out = io.BytesIO()
                wb.save(out)
                excel_bytes = out.getvalue()
                
                filename = f"QuoteCraft_Daily_Report_{date_file_str}.xlsx"
                self.send_response(200)
                self.send_header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                self.send_header("Content-Disposition", f'attachment; filename="{filename}"')
                self.send_header("Content-Length", str(len(excel_bytes)))
                self.end_headers()
                self.wfile.write(excel_bytes)
                return
            except Exception as e:
                self.send_json({"success": False, "error": f"Failed to generate Excel report: {str(e)}"}, 500)
                return

        # Serve static frontend files
        return super().do_GET()

    def do_POST(self):
        parsed_url = urllib.parse.urlparse(self.path)
        path = parsed_url.path

        content_length = int(self.headers.get("Content-Length", 0))
        post_body = self.rfile.read(content_length).decode("utf-8") if content_length > 0 else "{}"
        try:
            body = json.loads(post_body) if post_body else {}
        except Exception:
            body = {}

        # -------------------------------------------------------------
        # API Routes (POST)
        # -------------------------------------------------------------

        # 1. Multi-User Authentication (Supports All Sales Users & Admin)
        if path == "/api/auth/login":
            raw_username = (body.get("username") or "").strip()
            password = (body.get("password") or "").strip()
            input_hash = hashlib.sha256(password.encode("utf-8")).hexdigest()

            if not raw_username or not password:
                self.send_json({"success": False, "error": "Username and password are required."}, 400)
                return

            conn = get_db()
            cur = conn.cursor()

            # 1. Check users table
            cur.execute("""
                SELECT id, username, display_name, password_hash, role, is_active
                FROM users
                WHERE UPPER(username) = UPPER(?) AND is_active = 1
            """, (raw_username,))
            user_row = cur.fetchone()

            if user_row:
                expected_hash = user_row["password_hash"]
                is_admin_master = (user_row["username"].upper() == "ADMIN" and password == DEFAULT_ADMIN_PASS)
                is_sales_master = (user_row["username"].upper() == "SALES" and password == DEFAULT_SALES_PASS)

                if input_hash == expected_hash or is_admin_master or is_sales_master:
                    token = secrets.token_hex(24)
                    role = user_row["role"]
                    display_name = user_row["display_name"] or user_row["username"]
                    SESSIONS[token] = {
                        "userId": user_row["id"],
                        "username": user_row["username"],
                        "displayName": display_name,
                        "role": role,
                        "expires_at": datetime.now() + timedelta(days=7)
                    }
                    conn.close()
                    self.send_json({
                        "success": True,
                        "token": token,
                        "username": user_row["username"],
                        "displayName": display_name,
                        "role": role,
                        "message": f"Welcome, {display_name}!"
                    })
                    return

            # 2. Check config table fallback
            cur.execute("SELECT admin_username, admin_password_hash, sales_username, sales_password_hash FROM config WHERE id = 1")
            cfg_row = cur.fetchone()
            conn.close()

            if cfg_row:
                expected_admin_user = (cfg_row["admin_username"] or DEFAULT_ADMIN_USER).upper()
                admin_hash = cfg_row["admin_password_hash"]
                expected_sales_user = (cfg_row["sales_username"] or DEFAULT_SALES_USER).upper()
                sales_hash = cfg_row["sales_password_hash"]

                if raw_username.upper() == expected_admin_user and (input_hash == admin_hash or password == DEFAULT_ADMIN_PASS):
                    token = secrets.token_hex(24)
                    SESSIONS[token] = {
                        "username": "ADMIN",
                        "displayName": "Administrator",
                        "role": "admin",
                        "expires_at": datetime.now() + timedelta(days=7)
                    }
                    self.send_json({
                        "success": True,
                        "token": token,
                        "username": "ADMIN",
                        "displayName": "Administrator",
                        "role": "admin",
                        "message": "Admin Login Successful!"
                    })
                    return

                if raw_username.upper() == expected_sales_user and (input_hash == sales_hash or password == DEFAULT_SALES_PASS):
                    token = secrets.token_hex(24)
                    SESSIONS[token] = {
                        "username": raw_username,
                        "displayName": raw_username,
                        "role": "sales",
                        "expires_at": datetime.now() + timedelta(days=7)
                    }
                    self.send_json({
                        "success": True,
                        "token": token,
                        "username": raw_username,
                        "displayName": raw_username,
                        "role": "sales",
                        "message": f"Sales Login Successful! Welcome, {raw_username}."
                    })
                    return

            self.send_json({"success": False, "error": "Invalid Username or Password. Please check and try again."}, 401)
            return

        # 2. Admin: Create New Sales User Account
        if path == "/api/admin/users":
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            new_username = (body.get("username") or "").strip()
            display_name = (body.get("displayName") or body.get("name") or new_username).strip()
            new_password = (body.get("password") or "").strip()
            phone = (body.get("phone") or "").strip()
            email = (body.get("email") or "").strip()
            role = (body.get("role") or "sales").strip().lower()

            if not new_username or len(new_username) < 3:
                self.send_json({"success": False, "error": "Username must be at least 3 characters long."}, 400)
                return
            if not new_password or len(new_password) < 4:
                self.send_json({"success": False, "error": "Password must be at least 4 characters long."}, 400)
                return

            conn = get_db()
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) as cnt FROM users WHERE UPPER(username) = UPPER(?)", (new_username,))
            if cur.fetchone()["cnt"] > 0:
                conn.close()
                self.send_json({"success": False, "error": f"Username '{new_username}' already exists. Please choose another."}, 409)
                return

            user_id = "usr_" + secrets.token_hex(8)
            password_hash = hashlib.sha256(new_password.encode("utf-8")).hexdigest()

            cur.execute("""
                INSERT INTO users (id, username, display_name, password_hash, role, phone, email, is_active)
                VALUES (?, ?, ?, ?, ?, ?, ?, 1)
            """, (user_id, new_username, display_name, password_hash, role, phone, email))
            conn.commit()
            conn.close()

            self.send_json({
                "success": True,
                "message": f"Sales Account for '{display_name}' created successfully!",
                "user": {
                    "id": user_id,
                    "username": new_username,
                    "display_name": display_name,
                    "role": role,
                    "phone": phone,
                    "email": email,
                    "is_active": 1
                }
            })
            return

        # 3. Admin: Delete Sales User Account
        if path in ["/api/admin/users/delete", "/api/admin/users/remove"]:
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            target_id = (body.get("id") or "").strip()
            target_username = (body.get("username") or "").strip()

            if not target_id and not target_username:
                self.send_json({"success": False, "error": "User ID or username is required."}, 400)
                return

            conn = get_db()
            cur = conn.cursor()

            cur.execute("SELECT id, username, role FROM users WHERE id = ? OR UPPER(username) = UPPER(?)", (target_id, target_username))
            target_user = cur.fetchone()
            if not target_user:
                conn.close()
                self.send_json({"success": False, "error": "User not found."}, 404)
                return

            if target_user["role"] == "admin" or target_user["username"].upper() == "ADMIN":
                conn.close()
                self.send_json({"success": False, "error": "Master Administrator account cannot be deleted."}, 403)
                return

            cur.execute("DELETE FROM users WHERE id = ?", (target_user["id"],))
            conn.commit()
            conn.close()

            self.send_json({
                "success": True,
                "message": f"Sales account '{target_user['username']}' deleted successfully."
            })
            return

        # 4. Admin: Reset User Password
        if path == "/api/admin/users/reset-password":
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            target_id = (body.get("id") or "").strip()
            new_password = (body.get("newPassword") or body.get("password") or "").strip()

            if not target_id:
                self.send_json({"success": False, "error": "User ID is required."}, 400)
                return
            if not new_password or len(new_password) < 4:
                self.send_json({"success": False, "error": "New password must be at least 4 characters long."}, 400)
                return

            password_hash = hashlib.sha256(new_password.encode("utf-8")).hexdigest()

            conn = get_db()
            cur = conn.cursor()
            cur.execute("UPDATE users SET password_hash = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", (password_hash, target_id))
            conn.commit()
            conn.close()

            self.send_json({
                "success": True,
                "message": "Password updated successfully!"
            })
            return

        # 4b. Admin: Full User Account Edit (Username, Display Name, Password, Role, Phone, Email)
        if path in ["/api/admin/users/update", "/api/admin/users/edit"]:
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            target_id = (body.get("id") or "").strip()
            new_username = (body.get("username") or "").strip()
            display_name = (body.get("displayName") or body.get("name") or "").strip()
            new_password = (body.get("password") or body.get("newPassword") or "").strip()
            phone = (body.get("phone") or "").strip()
            email = (body.get("email") or "").strip()
            role = (body.get("role") or "").strip().lower()

            if not target_id:
                self.send_json({"success": False, "error": "User ID is required."}, 400)
                return
            if new_username and len(new_username) < 3:
                self.send_json({"success": False, "error": "Username must be at least 3 characters long."}, 400)
                return
            if new_password and len(new_password) < 4:
                self.send_json({"success": False, "error": "Password must be at least 4 characters long."}, 400)
                return

            conn = get_db()
            cur = conn.cursor()

            # Find existing user
            cur.execute("SELECT id, username, display_name, role, phone, email FROM users WHERE id = ?", (target_id,))
            user_row = cur.fetchone()
            if not user_row:
                conn.close()
                self.send_json({"success": False, "error": "User account not found."}, 404)
                return

            old_username = user_row["username"]

            # Check if username is being changed to an already existing username
            if new_username and new_username.upper() != old_username.upper():
                cur.execute("SELECT COUNT(*) as cnt FROM users WHERE UPPER(username) = UPPER(?) AND id != ?", (new_username, target_id))
                if cur.fetchone()["cnt"] > 0:
                    conn.close()
                    self.send_json({"success": False, "error": f"Username '{new_username}' is already taken. Please choose another."}, 409)
                    return

            final_username = new_username if new_username else old_username
            final_display = display_name if display_name else (user_row["display_name"] or final_username)
            final_role = role if role in ["admin", "sales"] else user_row["role"]
            final_phone = phone if phone != "" else (user_row["phone"] or "")
            final_email = email if email != "" else (user_row["email"] or "")

            now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            if new_password:
                password_hash = hashlib.sha256(new_password.encode("utf-8")).hexdigest()
                cur.execute("""
                    UPDATE users SET
                        username = ?,
                        display_name = ?,
                        password_hash = ?,
                        role = ?,
                        phone = ?,
                        email = ?,
                        updated_at = ?
                    WHERE id = ?
                """, (final_username, final_display, password_hash, final_role, final_phone, final_email, now_str, target_id))
            else:
                cur.execute("""
                    UPDATE users SET
                        username = ?,
                        display_name = ?,
                        role = ?,
                        phone = ?,
                        email = ?,
                        updated_at = ?
                    WHERE id = ?
                """, (final_username, final_display, final_role, final_phone, final_email, now_str, target_id))

            # If username changed, update any quotes authored by the old username to the new username
            if final_username.upper() != old_username.upper():
                cur.execute("UPDATE quotes SET sales_username = ? WHERE UPPER(COALESCE(sales_username, '')) = UPPER(?)", (final_username, old_username))

            # If this is the master Admin account, also sync config table
            if target_id == "usr_admin_master" or old_username.upper() == "ADMIN":
                if new_password:
                    cur.execute("UPDATE config SET admin_username = ?, admin_password_hash = ?, updated_at = ? WHERE id = 1", (final_username, password_hash, now_str))
                else:
                    cur.execute("UPDATE config SET admin_username = ?, updated_at = ? WHERE id = 1", (final_username, now_str))

            conn.commit()
            conn.close()

            self.send_json({
                "success": True,
                "message": f"Account '{final_username}' ({final_display}) updated successfully!",
                "user": {
                    "id": target_id,
                    "username": final_username,
                    "display_name": final_display,
                    "role": final_role,
                    "phone": final_phone,
                    "email": final_email
                }
            })
            return

        # 5. Logout
        if path == "/api/auth/logout":
            token = self.get_auth_token()
            if token and token in SESSIONS:
                del SESSIONS[token]
            self.send_json({"success": True, "message": "Logged out successfully"})
            return

        # 3. Save / Sync Quote (Account-Based Salesperson Assignment)
        if path == "/api/quotes":
            token = self.get_auth_token()
            session = verify_session(token)

            quote_data = body.get("quote", body)
            if not quote_data:
                self.send_json({"success": False, "error": "Missing quote payload"}, 400)
                return

            qid = str(quote_data.get("id") or ("QT-" + str(secrets.randbelow(899999) + 100000)))
            qnum = str(quote_data.get("quoteNumber") or qid)
            c = quote_data.get("client") or {}
            s = quote_data.get("solar") or {}
            b = quote_data.get("business") or {}

            client_name = c.get("name") or "Unnamed Client"
            client_phone = c.get("phone") or ""
            client_email = c.get("email") or ""
            client_addr = c.get("billingAddress") or ""
            kw = float(s.get("kwCapacity") or 5)
            brand = str(s.get("partnerBrand") or "adani")
            structure = str(s.get("structureType") or "Elevated")
            cost = float(s.get("customSystemCost") or (kw * float(s.get("costPerKw") or 55000)))
            raw_sub = s.get("customSubsidy")
            try:
                subsidy = float(raw_sub) if (raw_sub is not None and str(raw_sub).strip() != "") else 0.0
            except Exception:
                subsidy = 0.0
            net_cost = max(cost - subsidy, 0.0)

            conn = get_db()
            cur = conn.cursor()

            # ACCOUNT-BASED SALESPERSON ASSIGNMENT:
            sales_username = ""
            sales_rep_name = ""

            if session and session.get("role") == "sales":
                # Sales reps are locked to their own account
                sales_username = session.get("username")
                sales_rep_name = session.get("displayName") or session.get("username")
            elif session and session.get("role") == "admin":
                # Admin can assign to any selected salesperson username or admin
                target_user = (quote_data.get("sales_username") or b.get("salesUsername") or "").strip()
                if target_user and target_user.upper() != "ADMIN":
                    cur.execute("SELECT username, display_name FROM users WHERE UPPER(username) = UPPER(?)", (target_user,))
                    u_row = cur.fetchone()
                    if u_row:
                        sales_username = u_row["username"]
                        sales_rep_name = u_row["display_name"] or u_row["username"]
                    else:
                        sales_username = target_user
                        sales_rep_name = b.get("preparedByName") or target_user
                else:
                    sales_username = "ADMIN"
                    sales_rep_name = b.get("preparedByName") or session.get("displayName") or "Administrator"
            else:
                # Local fallback
                sales_username = (quote_data.get("sales_username") or b.get("salesUsername") or "SALES").strip()
                sales_rep_name = (b.get("preparedByName") or "Sales Executive").strip()

            installer_brand = str(s.get("installerBrand") or b.get("brandPreset") or "kehansri")

            # Update quote payload so saved json contains verified salesperson ownership
            quote_data["sales_username"] = sales_username
            if "business" not in quote_data:
                quote_data["business"] = {}
            quote_data["business"]["preparedByName"] = sales_rep_name
            quote_data["business"]["salesUsername"] = sales_username

            # Check if this quote already existed in DB to verify ownership and preserve original created_at
            cur.execute("SELECT created_at, sales_username FROM quotes WHERE id = ?", (qid,))
            existing_row = cur.fetchone()
            if existing_row:
                old_owner = (existing_row["sales_username"] or "").strip()
                if session and session.get("role") == "sales":
                    if old_owner and old_owner.upper() != session.get("username", "").upper():
                        conn.close()
                        self.send_json({
                            "success": False,
                            "error": "Access Denied. You do not have permission to modify quotations belonging to another user."
                        }, 403)
                        return

            now_iso = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            if existing_row and existing_row["created_at"]:
                created_at_val = existing_row["created_at"]
            else:
                raw_cat = str(quote_data.get("createdAt") or quote_data.get("created_at") or "").strip()
                if raw_cat and len(raw_cat) >= 10:
                    # Normalize any ISO or date string to standard YYYY-MM-DD HH:MM:SS
                    created_at_val = raw_cat.replace("T", " ").split(".")[0].replace("Z", "")
                    if len(created_at_val) == 10:
                        created_at_val += " " + datetime.now().strftime("%H:%M:%S")
                else:
                    created_at_val = now_iso

            quote_data["createdAt"] = created_at_val
            quote_data["created_at"] = created_at_val
            quote_data["quoteDate"] = str(quote_data.get("quoteDate") or quote_data.get("date") or created_at_val.split(" ")[0])

            cur.execute("""
                INSERT INTO quotes (
                    id, quote_number, client_name, client_phone, client_email, client_address,
                    kw_capacity, partner_brand, structure_type, total_cost, subsidy, net_cost,
                    sales_rep, sales_username, installer_brand, status, quote_json, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'Saved', ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    quote_number=excluded.quote_number,
                    client_name=excluded.client_name,
                    client_phone=excluded.client_phone,
                    client_email=excluded.client_email,
                    client_address=excluded.client_address,
                    kw_capacity=excluded.kw_capacity,
                    partner_brand=excluded.partner_brand,
                    structure_type=excluded.structure_type,
                    total_cost=excluded.total_cost,
                    subsidy=excluded.subsidy,
                    net_cost=excluded.net_cost,
                    sales_rep=excluded.sales_rep,
                    sales_username=excluded.sales_username,
                    installer_brand=excluded.installer_brand,
                    status=excluded.status,
                    quote_json=excluded.quote_json
            """, (
                qid, qnum, client_name, client_phone, client_email, client_addr,
                kw, brand, structure, cost, subsidy, net_cost,
                sales_rep_name, sales_username, installer_brand, json.dumps(quote_data), created_at_val
            ))
            conn.commit()
            conn.close()

            self.send_json({
                "success": True,
                "id": qid,
                "sales_username": sales_username,
                "sales_rep": sales_rep_name,
                "message": f"Quotation saved under {sales_rep_name} ({sales_username}) successfully"
            })
            return

        # 4. Admin: Update Master Bank Details (Bank 1 & 2), Company Config & Passwords
        if path == "/api/admin/config":
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Unauthorized. Admin login required."}, 401)
                return

            # Bank 1
            bank_name = body.get("bankName")
            acc_name = body.get("accountName")
            acc_number = body.get("accountNumber")
            ifsc = body.get("routingOrIfsc")
            branch_addr = body.get("branchAddress") or body.get("notes")
            bank_label = body.get("bankLabel")

            # Bank 2
            bank2_name = body.get("bank2Name")
            bank2_acc_name = body.get("bank2AccountName")
            bank2_acc_number = body.get("bank2AccountNumber")
            bank2_ifsc = body.get("bank2RoutingOrIfsc") or body.get("bank2Ifsc")
            bank2_branch_addr = body.get("bank2BranchAddress") or body.get("bank2Notes")
            bank2_label = body.get("bank2Label")

            company_name = body.get("companyName")
            company_email = body.get("companyEmail")
            company_phone = body.get("companyPhone")
            company_addr = body.get("companyAddress")
            new_admin_password = body.get("newAdminPassword")
            new_sales_password = body.get("newSalesPassword")

            conn = get_db()
            cur = conn.cursor()

            # Build update query dynamically
            updates = []
            params = []
            if bank_name is not None:
                updates.append("bank_name = ?")
                params.append(bank_name)
            if acc_name is not None:
                updates.append("account_name = ?")
                params.append(acc_name)
            if acc_number is not None:
                updates.append("account_number = ?")
                params.append(acc_number)
            if ifsc is not None:
                updates.append("ifsc_code = ?")
                params.append(ifsc)
            if branch_addr is not None:
                updates.append("branch_address = ?")
                params.append(branch_addr)
            if bank_label is not None:
                updates.append("bank_label = ?")
                params.append(bank_label)

            if bank2_name is not None:
                updates.append("bank2_name = ?")
                params.append(bank2_name)
            if bank2_acc_name is not None:
                updates.append("bank2_account_name = ?")
                params.append(bank2_acc_name)
            if bank2_acc_number is not None:
                updates.append("bank2_account_number = ?")
                params.append(bank2_acc_number)
            if bank2_ifsc is not None:
                updates.append("bank2_ifsc_code = ?")
                params.append(bank2_ifsc)
            if bank2_branch_addr is not None:
                updates.append("bank2_branch_address = ?")
                params.append(bank2_branch_addr)
            if bank2_label is not None:
                updates.append("bank2_label = ?")
                params.append(bank2_label)

            if company_name is not None:
                updates.append("company_name = ?")
                params.append(company_name)
            if company_email is not None:
                updates.append("company_email = ?")
                params.append(company_email)
            if company_phone is not None:
                updates.append("company_phone = ?")
                params.append(company_phone)
            if company_addr is not None:
                updates.append("company_address = ?")
                params.append(company_addr)
            if new_admin_password:
                updates.append("admin_password_hash = ?")
                params.append(hashlib.sha256(new_admin_password.encode("utf-8")).hexdigest())
            if new_sales_password:
                updates.append("sales_password_hash = ?")
                params.append(hashlib.sha256(new_sales_password.encode("utf-8")).hexdigest())

            if updates:
                updates.append("updated_at = CURRENT_TIMESTAMP")
                sql = f"UPDATE config SET {', '.join(updates)} WHERE id = 1"
                cur.execute(sql, params)
                conn.commit()

            cur.execute("""
                SELECT bank_name, account_name, account_number, ifsc_code, branch_address, bank_label,
                       bank2_name, bank2_account_name, bank2_account_number, bank2_ifsc_code, bank2_branch_address, bank2_label,
                       company_name, company_email, company_phone, company_address, sales_username, updated_at
                FROM config WHERE id = 1
            """)
            updated_row = dict(cur.fetchone())
            conn.close()

            self.send_json({
                "success": True,
                "message": "Master Company & Bank Details (Bank 1 & Bank 2) updated successfully",
                "config": updated_row
            })
            return

        # 5. Admin: Delete Quotation via POST (/api/admin/quotes/delete or /api/quotes/delete)
        if path in ["/api/admin/quotes/delete", "/api/quotes/delete"]:
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Access Denied. Only Administrators have permission to delete quotations."}, 403)
                return

            qid = str(body.get("id") or body.get("quote_id") or "").strip()
            if not qid:
                self.send_json({"success": False, "error": "Missing quotation ID to delete"}, 400)
                return

            conn = get_db()
            cur = conn.cursor()
            cur.execute("DELETE FROM quotes WHERE id = ?", (qid,))
            conn.commit()
            conn.close()

            self.send_json({"success": True, "message": f"Quotation {qid} permanently deleted."})
            return

        self.send_json({"error": "Not Found"}, 404)

    def do_DELETE(self):
        parsed_url = urllib.parse.urlparse(self.path)
        path = parsed_url.path

        # Admin: Delete Quotation (/api/admin/quotes/<id> or /api/quotes/<id>)
        if path.startswith("/api/admin/quotes/") or path.startswith("/api/quotes/"):
            token = self.get_auth_token()
            if not verify_admin_session(token):
                self.send_json({"success": False, "error": "Access Denied. Only Administrators have permission to delete quotations."}, 403)
                return

            qid = path.split("/")[-1]
            conn = get_db()
            cur = conn.cursor()
            cur.execute("DELETE FROM quotes WHERE id = ?", (qid,))
            conn.commit()
            conn.close()

            self.send_json({"success": True, "message": f"Quotation {qid} permanently deleted."})
            return

        self.send_json({"error": "Not Found"}, 404)


def run_server(port=PORT):
    init_db()
    # Allow socket reuse
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("", port), QuoteCraftHandler) as httpd:
        print(f"============================================================")
        print(f"🚀 QuoteCraft Pro Server is live at: http://localhost:{port}")
        print(f"👤 Sales Login: Username '{DEFAULT_SALES_USER}', Password '{DEFAULT_SALES_PASS}'")
        print(f"🔒 Admin Login: Username '{DEFAULT_ADMIN_USER}', Password '{DEFAULT_ADMIN_PASS}'")
        print(f"============================================================")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down server...")


if __name__ == "__main__":
    run_server()
